"""Deterministic pricing boundary."""

from __future__ import annotations

from quoteguard._compat import BaseModel, Field, ValidationError


class QuoteRequest(BaseModel):
    product_type: str
    property_type: str
    postcode: str
    security_features: str = ""
    occupancy: str

    def __post_init_model__(self) -> None:
        if self.product_type != "home_contents":
            raise ValidationError("QuoteRequest currently supports only home_contents")
        if len(self.postcode) != 4 or not self.postcode.isdigit():
            raise ValidationError("QuoteRequest.postcode must be a four-digit string")


class QuoteResponse(BaseModel):
    estimated_premium: float
    currency: str = "AUD"
    explanation: str = ""
    reference_id: str = Field(default="mock-price-v1")


def price_quote(request: QuoteRequest) -> QuoteResponse:
    base_price = 620.0
    if request.property_type == "apartment":
        base_price -= 55.0
    if request.occupancy == "tenant":
        base_price -= 35.0
    if "alarm" in request.security_features:
        base_price -= 20.0
    if request.postcode.startswith("3"):
        base_price += 25.0
    if request.postcode.startswith("2"):
        base_price += 40.0
    return QuoteResponse(
        estimated_premium=round(base_price, 2),
        explanation="Deterministic mock price generated by the pricing engine boundary.",
    )


def create_app():
    try:
        from fastapi import FastAPI
    except ImportError as exc:
        raise RuntimeError("FastAPI is not installed. Install project dependencies to run the API.") from exc

    app = FastAPI(title="QuoteGuard Pricing API")

    @app.post("/quote", response_model=dict)
    def quote_endpoint(payload: dict) -> dict:
        quote_request = QuoteRequest.model_validate(payload)
        return price_quote(quote_request).model_dump()

    return app


app = None
try:
    app = create_app()
except RuntimeError:
    app = None
